/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'hanweb\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-user' : '&#x21;',
			'icon-user-2' : '&#x22;',
			'icon-user-3' : '&#x23;',
			'icon-user-4' : '&#x24;',
			'icon-friends' : '&#x25;',
			'icon-users' : '&#x26;',
			'icon-user-5' : '&#x27;',
			'icon-plus-sign' : '&#x28;',
			'icon-minus-sign' : '&#x29;',
			'icon-remove-sign' : '&#x2a;',
			'icon-ok-sign' : '&#x2b;',
			'icon-plus' : '&#x2c;',
			'icon-minus' : '&#x2d;',
			'icon-checkmark' : '&#x2e;',
			'icon-cancel' : '&#x2f;',
			'icon-close' : '&#x30;',
			'icon-checkmark-2' : '&#x31;',
			'icon-trash' : '&#x32;',
			'icon-trash-2' : '&#x33;',
			'icon-trash-3' : '&#x34;',
			'icon-trashcan' : '&#x35;',
			'icon-trashcan-2' : '&#x36;',
			'icon-pen-alt-stroke' : '&#x37;',
			'icon-pen-alt-fill' : '&#x38;',
			'icon-pen' : '&#x39;',
			'icon-pencil' : '&#x3a;',
			'icon-th-large' : '&#x3b;',
			'icon-sitemap' : '&#x3c;',
			'icon-treediagram' : '&#x3d;',
			'icon-tree' : '&#x3e;',
			'icon-download' : '&#x3f;',
			'icon-upload' : '&#x40;',
			'icon-chevron-up' : '&#x41;',
			'icon-chevron-down' : '&#x42;',
			'icon-download-2' : '&#x43;',
			'icon-upload-2' : '&#x44;',
			'icon-folder-close' : '&#x45;',
			'icon-folder-open' : '&#x46;',
			'icon-check' : '&#x47;',
			'icon-checkbox' : '&#x48;',
			'icon-checkbox2' : '&#x49;',
			'icon-edit' : '&#x4a;',
			'icon-edit-2' : '&#x4b;',
			'icon-compose' : '&#x4c;',
			'icon-reliability' : '&#x4d;',
			'icon-list' : '&#x4e;',
			'icon-list-2' : '&#x4f;',
			'icon-menu' : '&#x50;',
			'icon-foldertree' : '&#x51;',
			'icon-download-3' : '&#x52;',
			'icon-upload-3' : '&#x53;',
			'icon-crop' : '&#x54;',
			'icon-crop-2' : '&#x55;',
			'icon-export' : '&#x56;',
			'icon-share' : '&#x57;',
			'icon-key' : '&#x58;',
			'icon-key-2' : '&#x59;',
			'icon-calendar' : '&#x5a;',
			'icon-calendar-2' : '&#x5b;',
			'icon-vcard' : '&#x5c;',
			'icon-vcard-2' : '&#x5d;',
			'icon-cog' : '&#x5e;',
			'icon-wrench' : '&#x5f;',
			'icon-websitebuilder' : '&#x60;',
			'icon-search' : '&#x61;',
			'icon-search-2' : '&#x62;',
			'icon-floppy' : '&#x63;',
			'icon-save' : '&#x64;',
			'icon-clock' : '&#x65;',
			'icon-stopwatch' : '&#x66;',
			'icon-alarm' : '&#x67;',
			'icon-locked' : '&#x68;',
			'icon-unlocked' : '&#x69;',
			'icon-qrcode' : '&#x6a;',
			'icon-qrcode-2' : '&#x6b;',
			'icon-barcode' : '&#x6c;',
			'icon-briefcase' : '&#x6d;',
			'icon-briefcase-2' : '&#x6e;',
			'icon-plugin' : '&#x6f;',
			'icon-puzzle' : '&#x70;',
			'icon-loop' : '&#x71;',
			'icon-refresh' : '&#x72;',
			'icon-print' : '&#x73;',
			'icon-shredder' : '&#x74;',
			'icon-copy' : '&#x75;',
			'icon-paste' : '&#x76;',
			'icon-forward' : '&#x77;',
			'icon-back' : '&#x78;',
			'icon-forward-2' : '&#x79;',
			'icon-reply' : '&#x7a;',
			'icon-undo' : '&#x7b;',
			'icon-reply-all' : '&#x7c;',
			'icon-reply-all-2' : '&#x7d;',
			'icon-forward-3' : '&#x7e;',
			'icon-undo-2' : '&#xe000;',
			'icon-redo' : '&#xe001;',
			'icon-forward-4' : '&#xe002;',
			'icon-reply-2' : '&#xe003;',
			'icon-undo-3' : '&#xe004;',
			'icon-redo-2' : '&#xe005;',
			'icon-cut' : '&#xe006;',
			'icon-scissors' : '&#xe007;',
			'icon-addfriend' : '&#xe008;',
			'icon-removefriend' : '&#xe009;',
			'icon-user-6' : '&#xe00a;',
			'icon-user-7' : '&#xe00b;',
			'icon-users-2' : '&#xe00c;',
			'icon-download-4' : '&#xe00d;',
			'icon-upload-4' : '&#xe00e;',
			'icon-signin' : '&#xe00f;',
			'icon-signout' : '&#xe010;',
			'icon-cloud-download' : '&#xe011;',
			'icon-cloud-upload' : '&#xe012;',
			'icon-upload-5' : '&#xe013;',
			'icon-download-5' : '&#xe014;',
			'icon-chart' : '&#xe015;',
			'icon-chart-2' : '&#xe016;',
			'icon-plug' : '&#xe017;',
			'icon-fourohfour' : '&#xe018;',
			'icon-inbox' : '&#xe019;',
			'icon-icons' : '&#xe01a;',
			'icon-attachment' : '&#xe01b;',
			'icon-chat' : '&#xe01c;',
			'icon-filter' : '&#xe01d;',
			'icon-signup' : '&#xe01e;',
			'icon-ipcontrol' : '&#xe01f;',
			'icon-rubberstamp' : '&#xe020;',
			'icon-sort' : '&#xe021;',
			'icon-algorhythm' : '&#xe022;',
			'icon-home' : '&#xe023;',
			'icon-html5' : '&#xe024;',
			'icon-database' : '&#xe025;',
			'icon-question' : '&#xe026;',
			'icon-remove' : '&#xe027;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};